# image of an OS
image: ubuntu:20.04

pytest:
  stage: test
  before_script:
    # update ubuntu
    - apt-get update
    # install pip
    - apt-get install -y python3-pip
    # install python packages
    - pip3 install numpy scipy pandas xarray pytest pytest-cov 
  script:
    # run pytest and unit test coverage report
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml --cov-config=.coveragerc
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

